---
title: "Course Project: Shiny Application and Reproducible Pitch"
author: "German Fajardo G"
date: "11 Feb 2019"
Folder: https://github.com/gafajardogr/ShinyApplicationReproduciblePitch/
URL to check presentation: https://gafajardog.shinyapps.io/ShinyApplicationReproduciblePitch/
output:
  slidy_presentation: default
  ioslides_presentation: default
  

---


## Instructions

This peer assessed assignment has two parts. First, you will create a Shiny application and deploy it on Rstudio's servers. Second, you will use Slidify or Rstudio Presenter to prepare a reproducible pitch presentation about your application.

Your Shiny Application

Write a shiny application with associated supporting documentation. The documentation should be thought of as whatever a user will need to get started using your application.
Deploy the application on Rstudio's shiny server
Share the application link by pasting it into the provided text box
Share your server.R and ui.R code on github
The application must include the following:

Some form of input (widget: textbox, radio button, checkbox, ...)
Some operation on the ui input in sever.R
Some reactive output displayed as a result of server calculations
You must also include enough documentation so that a novice user could use your application.
The documentation should be at the Shiny website itself. Do not post to an external link.
The Shiny application in question is entirely up to you. However, if you're having trouble coming up with ideas, you could start from the simple prediction algorithm done in class and build a new algorithm on one of the R datasets packages. Please make the package simple for the end user, so that they don't need a lot of your prerequisite knowledge to evaluate your application. You should emphasize a simple project given the short time frame.

## Shiny Application (Data mtcars)

This document focuses on the analysis of the R dataset mtcars.

The objective of the application is to make an explorer of the data to mtcar present in RStudio

1. Choose the variable of the following:
    'Cylinders' = 'cyl',
    'Miles / gallon' = 'mpg',
    'Displacement' = 'disp',
    'Quarter miles / sec' = 'qsec',
    'Gross horsepower' = 'hp',
    'Weight (lb / 1000)' = 'wt'
2. Select 'How do you want to check the points?'
    Plots or Tests
3. If you select 'Plots', you can paint
    Histogram, Boxplot, QQ plot
4 If you select Tests the program will show Shapiro-Wilk Test to check normality.
    The Shapiro-Wilk test is a statistical test used to test the normality of a data set. Published in 1965 by Samuel Shapiro and Martin Wilk.

## References
https://rstudio-pubs-static.s3.amazonaws.com/45786_b5e54c2d3c824f51abd2d559506cf81f.html







